from rsf.tex import *

for slides in glob.glob('slides???.tex'):
    slidesname = os.path.splitext(slides)[0]
    Paper(slidesname,
          lclass='cwpslides',
          use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy,framed',
          color='ALL',
          options='aspectratio=169')

Paper('segabs',
      lclass='segabs',
      options='notimes',
      use='natbib,graphicx,color,listings,amsmath,amssymb,amsbsy')

Paper('segcut',lclass='article',use='pdfpages,graphicx,color,listings,amsmath,amssymb,amsbsy,natbib')


for report in glob.glob('report*.tex'):
    name = os.path.splitext(report)[0]
    Paper(name,lclass='cwpreport',
          use='times,natbib,amsmath,graphicx,color,listings,amssymb,amsbsy,lineno,setspace,algorithmic,algorithm,framed',
          include=r'''
          \setlength{\paperwidth}{8.5in}
          \setlength{\paperheight}{11.0in}
          \setlength{\topmargin}{-0.25in}
          \setlength{\textheight}{8.75in}
          \setlength{\textwidth}{6.5in}
          \setlength{\oddsidemargin}{+.015625in}
          \setlength{\evensidemargin}{+.015625in}
          ''')


End(use='color')

